[package]
name = "git-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.18.3"
fuser = "0.15.1"
libc = "0.2"
tree-sitter = "0.25.3"
tree-sitter-rust = "0.21.0"

[dev-dependencies]
tempfile = "3.10.1"
