// This file represents the source code generated by the `smudge` filter.
// It uses a deterministic formatter (like rustfmt or dprint) to ensure
// consistent style, regardless of the original formatting.

fn add(a: i32, b: i32) -> i32 {
    // Simple addition
    a + b
}

fn main() {
    let x = 5;
    let y = 10;
    let sum = add(x, y);
    println!("Sum: {}", sum);
} 
